module.exports =  [
    'constructor()',
    'error IncorrectPayment(address user, uint256 amountSent)',
    'error NftLimitPerDirection(address user, uint256 balanceOf)',
    'error NftSoldOut(address user)',
    'error NotFondsToTranfer(address owner)',
    'error SaleNotStarted(address user)',
    'error TokenDoesNotExist()',
    'error UnsuccessfulPayout(address owner)',
    'event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)',
    'event ApprovalForAll(address indexed owner, address indexed operator, bool approved)',
    'event MintTheMetalorianDAOSilver(address indexed user, uint256 tokenId)',
    'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
    'event SetMintCost(address indexed owner, uint256 amount)',
    'event SetStartSale(address indexed owner, uint256 date)',
    'event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)',
    'event WithdrawProceeds(address indexed owner, uint256 amount)',
    'function AVAILABLE_SUPPLY() view returns (uint256)',
    'function LIMIT_NFT_BY_ADDRES() view returns (uint256)',
    'function approve(address to, uint256 tokenId)',
    'function balanceOf(address owner) view returns (uint256)',
    'function baseURI() view returns (string)',
    'function getApproved(uint256 tokenId) view returns (address)',
    'function isApprovedForAll(address owner, address operator) view returns (bool)',
    'function mintCost() view returns (uint256)',
    'function mintTheMetalorianDAOSilver(uint256 amountNft) payable',
    'function name() view returns (string)',
    'function owner() view returns (address)',
    'function ownerOf(uint256 tokenId) view returns (address)',
    'function renounceOwnership()',
    'function safeTransferFrom(address from, address to, uint256 tokenId)',
    'function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)',
    'function setApprovalForAll(address operator, bool approved)',
    'function setBaseURI(string setBaseUri)',
    'function setMintCost(uint256 newMintCost)',
    'function setStartSale(bool value)',
    'function startSale() view returns (bool)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function symbol() view returns (string)',
    'function tokenIdCounter() view returns (uint256 _value)',
    'function tokenURI(uint256 tokenId) view returns (string)',
    'function transferFrom(address from, address to, uint256 tokenId)',
    'function transferOwnership(address newOwner)',
    'function withdrawProceeds()'
]